spring:
  cloud:
    gateway:
      routes:
        - id: inventory-service
          uri: ${SERVICE_URL1:http://localhost:2011}
          predicates:
            - Path=/inventory/**

        - id: library-mvc-project
          uri: ${SERVICE_URL2:http://localhost:2010}
          predicates:
            - Path=/library/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:9091/eureka}

server:
  port: 9090
