spring:
  cloud:
    gateway:
      routes:
        - id: inventory-service
          uri: http://localhost:2011
          predicates:
            - Path=/inventory/**

        - id: library-mvc-project
          uri: http://localhost:2010
          predicates:
            - Path=/library/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9091/eureka

server:
  port: 9090
